name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    defaults:
      run:
        working-directory: naya-api

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Backend Tests
        env:
          MONGO_URI: mongodb://localhost:27017/canvasdb
        run: npm test

  integration-tests:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Backend Dependencies
        run: |
          cd naya-api
          npm install

      - name: Start Backend
        run: |
          cd naya-api
          npm run start &
        env:
          MONGO_URI: mongodb://localhost:27017/canvasdb

      - name: Install Frontend Dependencies
        run: |
          cd naya-web
          npm ci

      - name: Start Frontend
        run: |
          cd naya-web
          HOST=localhost npm start &

      - name: Wait for Services
        run: sleep 15  # Replace with health checks later if needed

      - name: Install Playwright Browsers
        run: |
          cd naya-web
          npx playwright install --with-deps

      - name: Run Playwright frontned and Integration Tests
        run: |
          cd naya-web
          npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-results
          path: playwright-report/
          retention-days: 3
